import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import MobileSidebar from "@/components/MobileSidebard";
import Providers from "@/components/Providers";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Harmonic Hues",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
